config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'articles#index'
  #get '/admin',to: 'articles#admin'

  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :articles do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  accepts_nested_attributes_for :comments,
    :allow_destroy => true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])

  end



  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  private

  def article_params
    params.require(:article).permit(:title, :subtitle, :body,
      comments_atributes: [:id, :_destroy])
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to admin_article_path(@article)
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

  end



  private

  def comment_params
    params.require(:comment).permit(:author,:content, :article_id, :id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "La Estampa"
    #article = Article.new(:title => "Muere Frizzi", :subtitle => "A los 60 años",
    #  body: "Era muy querido")
    #article.save
    end

  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

def create
  @article = Article.new(article_params)
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to admin_articles_path
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :body,
      comments_atributes: [:id, :_destroy])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  @article = Article.find(params[:article_id])
  @comment = @article.comments.create(comment_params)
  redirect_to article_path(@article)
end

def destroy
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id])
  @comment.destroy
  redirect_to admin_article_path(@article)
end

def update
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id])
  @comment.update(comment_params)
  redirect_to admin_article_path(@article)
end

private

def comment_params
  params.require(:comment).permit(:author,:content)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/articles/edit.html.erb
<h1>Editar Noticia</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@article) do |f| %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br><br>
    <%= f.label :subtitle %> <br>
    <%= f.text_area :subtitle %>
    <br><br>
    <%= f.label :body %> <br>
    <%= f.text_area :body%>
    <br> <br>
    <%= f.submit "Editar Noticia" %>

    <% end %>

  </div>
</div>

<%=link_to 'Atras', admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>Administrador de Noticias</h1>

<%= link_to 'Escribir Noticia', new_admin_article_path %>
<br>
<% articles = Article.all %>
<% articles.each do |article| %>
<%= article.title %> :
<%= article.body %>
<%= link_to 'Ver', admin_article_path(article) %> |
<%= link_to 'Editar', edit_admin_article_path(article) %> |
<%= link_to 'Eliminar', admin_article_path(article),
method: :delete,
data: { confirm: 'Are you sure?' } %>
<br>
<%end%>

<%=link_to 'Atras', articles_path %>

app/views/admin/articles/new.html.erb
<h1>Escribir Noticia</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@article) do |f| %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br><br>
    <%= f.label :subtitle %> <br>
    <%= f.text_area :subtitle %>
    <br><br>
    <%= f.label :body %> <br>
    <%= f.text_area :body%>
    <br> <br>
    <%= f.submit "Crear Noticia" %>

    <% end %>

  </div>
</div>

<%=link_to 'Atras', admin_articles_path %>

app/views/admin/articles/show.html.erb
admin
<h1><%= @article.title %></h1>
<h3><%= @article.subtitle %></h3>
<p><%= @article.body %></p>

<h3>Comentarios</h3>
<br>
<% @article.comments.each do |c| %>
<%= c.author %> :
<%= c.content %> |
<%= link_to 'Editar', edit_admin_article_comment_path(c.article,c) %>
<%= link_to 'Eliminar', [c.article, c], method: :delete,
data: { confirm: 'Are you sure?' } %>

<br>
<%end%>





  <%= link_to 'Atras', admin_articles_path %>

app/views/admin/comments/edit.html.erb
<%= form_for([@comment.article, @comment]) do |f|%>
  <%= f.label :nombre %>
  <%= f.text_field :author %>

  <%= f.label :comentario %>
  <%= f.text_field :content %>
  <%= f.submit %>

  <%end%>

  <%= link_to 'Atras', admin_article_path(@comment.article) %>

app/views/articles/admin.html.erb
<h1>Administrador de Noticias</h1>

<%= link_to 'Escribir Noticia', new_article_path %>
<br>
<% articles = Article.all %>
<% articles.each do |article| %>
<%= article.title %> :
<%= article.body %>
<%= link_to 'Ver', article_path(article) %> |
<%= link_to 'Editar', edit_article_path(article) %> |
<%= link_to 'Eliminar', article_path(article),
method: :delete,
data: { confirm: 'Are you sure?' } %>
<br>
<%end%>

<%=link_to 'Atras', articles_path %>

app/views/articles/edit.html.erb
<h1>Editar Noticia</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@article) do |f| %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br><br>
    <%= f.label :subtitle %> <br>
    <%= f.text_area :subtitle %>
    <br><br>
    <%= f.label :body %> <br>
    <%= f.text_area :body%>
    <br> <br>
    <%= f.submit "Editar Noticia" %>

    <% end %>

  </div>
</div>

<%=link_to 'Atras', '/admin' %>

app/views/articles/index.html.erb
<h1>La Estampaa</h1>

<% articles = Article.all %>
<% articles.each do |article| %>
  <%= article.title %> :
  <%= article.body %>
  <%= link_to 'Ver', article_path(article) %>
  <br>
  <%end%>

  <%= link_to 'Admin', admin_articles_path%>

app/views/articles/new.html.erb
<h1>Escribir Noticia</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@article) do |f| %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br><br>
    <%= f.label :subtitle %> <br>
    <%= f.text_area :subtitle %>
    <br><br>
    <%= f.label :body %> <br>
    <%= f.text_area :body%>
    <br> <br>
    <%= f.submit "Crear Noticia" %>

    <% end %>

  </div>
</div>

app/views/articles/show.html.erb
normal
<h1><%= @article.title %></h1>
<h3><%= @article.subtitle %></h3>
<p><%= @article.body %></p>

<h3>Comentarios</h3>
<br>
<% @article.comments.each do |c| %>
<%= c.author %> :
<%= c.content %>
<br>
<%end%>

<br>
Escribir comentario:

<%= form_with(model: [ @article, @article.comments.build ], local: true) do |f|%>
  <%= f.label :nombre %>
  <%= f.text_field :author %>

  <%= f.label :comentario %>
  <%= f.text_field :content %>
  <%= f.submit %>

  <%end%>

  <%= link_to 'Atras', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>